name: yaib_updated
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - black=22.0.8
  - flake8=5.0.4
  - gin-config=0.5.0
  - ignite=0.4.10
  - lightgbm=3.3.2
  - numpy=1.23.3
  - pandas=1.4.4
  - pyarrow=9.0.0
  - pytest=7.1.2
  - python=3.9.13
  - pytorch=1.12.1
  - scikit-learn=1.1.1
  - tensorboard=2.10.0
  - tqdm=4.64.1
