name: yaib
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - black
  - coverage
  - flake8
  - gin-config
  - ignite
  - lightgbm
  - numpy
  - pandas
  - pyarrow
  - pytest
  - pytorch=1.12.1
  - cudatoolkit=11.6.0
  - scikit-learn
  - tensorboard
  - tqdm
