lr: 0.002
d_k: 32
d_v: 32
seed: 1111
model: SAITS
epochs: 50
n_head: 4
Adam.lr: 0.001
d_inner: 128
d_model: 128
dropout: 0.1
data_dir: demo_data/simulated/seasonal
lr_steps: None
momentum: 0.9
n_layers: 2
run-name: run_SAITS_seasonal
run_mode: imputation
SAITS.d_k: 32
SAITS.d_v: 32
lr_factor: 0.99
input_size: [64, 200, 2]
input_shape: None
SAITS.n_head: 4
lr_scheduler: 
SAITS.d_inner: 128
SAITS.d_model: 128
SAITS.dropout: 0.1
SAITS.n_layers: 2
initialization_method: NORMAL
pretrained_imputation_model: None
execute_repeated_cv.cv_folds: 5
ImputationDataset.mask_method: BO
UncertaintyImputationWrapper.lr_scheduler: 
execute_repeated_cv.cv_repetitions: 2
execute_repeated_cv.cv_folds_to_train: 1
execute_repeated_cv.cv_repetitions_to_train: 1
