seed: 1111
model: SAITS
Adam.lr: 0.001
data_dir: demo_data/simulated/sinusoids
run-name: run_SAITS_sinusoids
SAITS.d_k: 32
SAITS.d_v: 64
SAITS.n_head: 8
SAITS.d_inner: 128
SAITS.d_model: 128
SAITS.dropout: 0.1
SAITS.n_layers: 2
pretrained_imputation_model: None
execute_repeated_cv.cv_folds: 5
ImputationDataset.mask_method: MAR
UncertaintyImputationWrapper.lr_scheduler: 
execute_repeated_cv.cv_repetitions: 2
execute_repeated_cv.cv_folds_to_train: 1
execute_repeated_cv.cv_repetitions_to_train: 1
