name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: icu-benchmark
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
    - name: setup package
      run: pip install -e .
    - name: test command line tool
      run: icu-benchmarks --help
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
