name: Lint and test recipes

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # needed for miniconda
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: yaib_updated
          environment-file: environment.yml
          auto-activate-base: false
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: python -m pytest ./tests/recipes
      # If we want to test running the tool later on
      # - name: setup package
      #   run: pip install -e .
      # - name: test command line tool
      #   run: python -m icu_benchmarks.run --help
